/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAppointmentsRouteImport } from './routes/api/appointments'
import { Route as ApiTestEmailRouteImport } from './routes/api/test-email'
import { Route as ApiAppointmentsAcceptRouteImport } from './routes/api/appointments/accept'
import { Route as ApiAppointmentsRejectRouteImport } from './routes/api/appointments/reject'
import { Route as ApiCronRemindersRouteImport } from './routes/api/cron/reminders'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAppointmentsRoute = ApiAppointmentsRouteImport.update({
  id: '/api/appointments',
  path: '/api/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTestEmailRoute = ApiTestEmailRouteImport.update({
  id: '/api/test-email',
  path: '/api/test-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAppointmentsAcceptRoute = ApiAppointmentsAcceptRouteImport.update({
  id: '/accept',
  path: '/accept',
  getParentRoute: () => ApiAppointmentsRoute,
} as any)
const ApiAppointmentsRejectRoute = ApiAppointmentsRejectRouteImport.update({
  id: '/reject',
  path: '/reject',
  getParentRoute: () => ApiAppointmentsRoute,
} as any)
const ApiCronRemindersRoute = ApiCronRemindersRouteImport.update({
  id: '/api/cron/reminders',
  path: '/api/cron/reminders',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/appointments': typeof ApiAppointmentsRouteWithChildren
  '/api/test-email': typeof ApiTestEmailRoute
  '/api/appointments/accept': typeof ApiAppointmentsAcceptRoute
  '/api/appointments/reject': typeof ApiAppointmentsRejectRoute
  '/api/cron/reminders': typeof ApiCronRemindersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/appointments': typeof ApiAppointmentsRouteWithChildren
  '/api/test-email': typeof ApiTestEmailRoute
  '/api/appointments/accept': typeof ApiAppointmentsAcceptRoute
  '/api/appointments/reject': typeof ApiAppointmentsRejectRoute
  '/api/cron/reminders': typeof ApiCronRemindersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/appointments': typeof ApiAppointmentsRouteWithChildren
  '/api/test-email': typeof ApiTestEmailRoute
  '/api/appointments/accept': typeof ApiAppointmentsAcceptRoute
  '/api/appointments/reject': typeof ApiAppointmentsRejectRoute
  '/api/cron/reminders': typeof ApiCronRemindersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/appointments'
    | '/api/test-email'
    | '/api/appointments/accept'
    | '/api/appointments/reject'
    | '/api/cron/reminders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/appointments'
    | '/api/test-email'
    | '/api/appointments/accept'
    | '/api/appointments/reject'
    | '/api/cron/reminders'
  id:
    | '__root__'
    | '/'
    | '/api/appointments'
    | '/api/test-email'
    | '/api/appointments/accept'
    | '/api/appointments/reject'
    | '/api/cron/reminders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAppointmentsRoute: typeof ApiAppointmentsRouteWithChildren
  ApiTestEmailRoute: typeof ApiTestEmailRoute
  ApiCronRemindersRoute: typeof ApiCronRemindersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/appointments': {
      id: '/api/appointments'
      path: '/api/appointments'
      fullPath: '/api/appointments'
      preLoaderRoute: typeof ApiAppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/test-email': {
      id: '/api/test-email'
      path: '/api/test-email'
      fullPath: '/api/test-email'
      preLoaderRoute: typeof ApiTestEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/appointments/accept': {
      id: '/api/appointments/accept'
      path: '/accept'
      fullPath: '/api/appointments/accept'
      preLoaderRoute: typeof ApiAppointmentsAcceptRouteImport
      parentRoute: typeof ApiAppointmentsRoute
    }
    '/api/appointments/reject': {
      id: '/api/appointments/reject'
      path: '/reject'
      fullPath: '/api/appointments/reject'
      preLoaderRoute: typeof ApiAppointmentsRejectRouteImport
      parentRoute: typeof ApiAppointmentsRoute
    }
    '/api/cron/reminders': {
      id: '/api/cron/reminders'
      path: '/api/cron/reminders'
      fullPath: '/api/cron/reminders'
      preLoaderRoute: typeof ApiCronRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiAppointmentsRouteChildren {
  ApiAppointmentsAcceptRoute: typeof ApiAppointmentsAcceptRoute
  ApiAppointmentsRejectRoute: typeof ApiAppointmentsRejectRoute
}

const ApiAppointmentsRouteChildren: ApiAppointmentsRouteChildren = {
  ApiAppointmentsAcceptRoute: ApiAppointmentsAcceptRoute,
  ApiAppointmentsRejectRoute: ApiAppointmentsRejectRoute,
}

const ApiAppointmentsRouteWithChildren = ApiAppointmentsRoute._addFileChildren(
  ApiAppointmentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAppointmentsRoute: ApiAppointmentsRouteWithChildren,
  ApiTestEmailRoute: ApiTestEmailRoute,
  ApiCronRemindersRoute: ApiCronRemindersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
