/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTestEmailRouteImport } from './routes/api/test-email'
import { Route as ApiCronRemindersRouteImport } from './routes/api/cron/reminders'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTestEmailRoute = ApiTestEmailRouteImport.update({
  id: '/api/test-email',
  path: '/api/test-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronRemindersRoute = ApiCronRemindersRouteImport.update({
  id: '/api/cron/reminders',
  path: '/api/cron/reminders',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/test-email': typeof ApiTestEmailRoute
  '/api/cron/reminders': typeof ApiCronRemindersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/test-email': typeof ApiTestEmailRoute
  '/api/cron/reminders': typeof ApiCronRemindersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/test-email': typeof ApiTestEmailRoute
  '/api/cron/reminders': typeof ApiCronRemindersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/test-email' | '/api/cron/reminders'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/test-email' | '/api/cron/reminders'
  id: '__root__' | '/' | '/api/test-email' | '/api/cron/reminders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiTestEmailRoute: typeof ApiTestEmailRoute
  ApiCronRemindersRoute: typeof ApiCronRemindersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/test-email': {
      id: '/api/test-email'
      path: '/api/test-email'
      fullPath: '/api/test-email'
      preLoaderRoute: typeof ApiTestEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/reminders': {
      id: '/api/cron/reminders'
      path: '/api/cron/reminders'
      fullPath: '/api/cron/reminders'
      preLoaderRoute: typeof ApiCronRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiTestEmailRoute: ApiTestEmailRoute,
  ApiCronRemindersRoute: ApiCronRemindersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
